### ISSUE TITLE
The icon is hardcoded

### ISSUE THREAD

**Issue by bilelmoussaoui** [Philip-Scott/iViewer#8]
Hello,
could you change the icon line to the /usr/share/icons/hicolor/apps? 
so its could be possible to change the icon by only changing the theme!

And if you can write a bash script to install the app? (copy folders/files and stuff..) for beginners ;) 
Thank you!

**Comment by Philip-Scott** [comment]
The icon is actually something I'm planning on doing by the next release :) The app should be installed system wide and not "locally" on the user's home directory.

But about the a bash script.... Making it is pretty trivial, but beginners shouldn't really be encouraged to just execute a random bash script, at least by having them execute the commands separately you can get an idea on what you're doing ;) But I'll think about it since having a "System-wide" install might require to run a lot more commands

**Comment by bilelmoussaoui** [comment]
I asked for an iViewer icon for Numix theme https://github.com/numixproject/numix-icon-theme-circle/issues/1603#issuecomment-76073210 and its would be very nice if you could tell us the icon line you are going to use later ;) 
Thanks
